// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_server.proto

#ifndef PROTOBUF_client_5fserver_2eproto__INCLUDED
#define PROTOBUF_client_5fserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace C2SPacket {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_client_5fserver_2eproto();
void protobuf_AssignDesc_client_5fserver_2eproto();
void protobuf_ShutdownFile_client_5fserver_2eproto();

class PktRegisterClient;

// ===================================================================

class PktRegisterClient : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:C2SPacket.PktRegisterClient) */ {
 public:
  PktRegisterClient();
  virtual ~PktRegisterClient();

  PktRegisterClient(const PktRegisterClient& from);

  inline PktRegisterClient& operator=(const PktRegisterClient& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PktRegisterClient& default_instance();

  void Swap(PktRegisterClient* other);

  // implements Message ----------------------------------------------

  inline PktRegisterClient* New() const { return New(NULL); }

  PktRegisterClient* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PktRegisterClient& from);
  void MergeFrom(const PktRegisterClient& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PktRegisterClient* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 client_info = 1;
  void clear_client_info();
  static const int kClientInfoFieldNumber = 1;
  ::google::protobuf::int32 client_info() const;
  void set_client_info(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:C2SPacket.PktRegisterClient)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 client_info_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_client_5fserver_2eproto();
  friend void protobuf_AssignDesc_client_5fserver_2eproto();
  friend void protobuf_ShutdownFile_client_5fserver_2eproto();

  void InitAsDefaultInstance();
  static PktRegisterClient* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PktRegisterClient

// optional int32 client_info = 1;
inline void PktRegisterClient::clear_client_info() {
  client_info_ = 0;
}
inline ::google::protobuf::int32 PktRegisterClient::client_info() const {
  // @@protoc_insertion_point(field_get:C2SPacket.PktRegisterClient.client_info)
  return client_info_;
}
inline void PktRegisterClient::set_client_info(::google::protobuf::int32 value) {
  
  client_info_ = value;
  // @@protoc_insertion_point(field_set:C2SPacket.PktRegisterClient.client_info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace C2SPacket

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_client_5fserver_2eproto__INCLUDED
