// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_server.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "server_server.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace S2SPacket {

namespace {

const ::google::protobuf::Descriptor* PktRegisterServer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PktRegisterServer_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_server_5fserver_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_server_5fserver_2eproto() {
  protobuf_AddDesc_server_5fserver_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "server_server.proto");
  GOOGLE_CHECK(file != NULL);
  PktRegisterServer_descriptor_ = file->message_type(0);
  static const int PktRegisterServer_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRegisterServer, server_info_),
  };
  PktRegisterServer_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PktRegisterServer_descriptor_,
      PktRegisterServer::default_instance_,
      PktRegisterServer_offsets_,
      -1,
      -1,
      -1,
      sizeof(PktRegisterServer),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRegisterServer, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRegisterServer, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_server_5fserver_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PktRegisterServer_descriptor_, &PktRegisterServer::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_server_5fserver_2eproto() {
  delete PktRegisterServer::default_instance_;
  delete PktRegisterServer_reflection_;
}

void protobuf_AddDesc_server_5fserver_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_server_5fserver_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023server_server.proto\022\tS2SPacket\"(\n\021PktR"
    "egisterServer\022\023\n\013server_info\030\001 \001(\005b\006prot"
    "o3", 82);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "server_server.proto", &protobuf_RegisterTypes);
  PktRegisterServer::default_instance_ = new PktRegisterServer();
  PktRegisterServer::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_server_5fserver_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_server_5fserver_2eproto {
  StaticDescriptorInitializer_server_5fserver_2eproto() {
    protobuf_AddDesc_server_5fserver_2eproto();
  }
} static_descriptor_initializer_server_5fserver_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PktRegisterServer::kServerInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PktRegisterServer::PktRegisterServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:S2SPacket.PktRegisterServer)
}

void PktRegisterServer::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PktRegisterServer::PktRegisterServer(const PktRegisterServer& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:S2SPacket.PktRegisterServer)
}

void PktRegisterServer::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  server_info_ = 0;
}

PktRegisterServer::~PktRegisterServer() {
  // @@protoc_insertion_point(destructor:S2SPacket.PktRegisterServer)
  SharedDtor();
}

void PktRegisterServer::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PktRegisterServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PktRegisterServer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PktRegisterServer_descriptor_;
}

const PktRegisterServer& PktRegisterServer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_server_5fserver_2eproto();
  return *default_instance_;
}

PktRegisterServer* PktRegisterServer::default_instance_ = NULL;

PktRegisterServer* PktRegisterServer::New(::google::protobuf::Arena* arena) const {
  PktRegisterServer* n = new PktRegisterServer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PktRegisterServer::Clear() {
// @@protoc_insertion_point(message_clear_start:S2SPacket.PktRegisterServer)
  server_info_ = 0;
}

bool PktRegisterServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:S2SPacket.PktRegisterServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 server_info = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &server_info_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:S2SPacket.PktRegisterServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:S2SPacket.PktRegisterServer)
  return false;
#undef DO_
}

void PktRegisterServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:S2SPacket.PktRegisterServer)
  // optional int32 server_info = 1;
  if (this->server_info() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->server_info(), output);
  }

  // @@protoc_insertion_point(serialize_end:S2SPacket.PktRegisterServer)
}

::google::protobuf::uint8* PktRegisterServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:S2SPacket.PktRegisterServer)
  // optional int32 server_info = 1;
  if (this->server_info() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->server_info(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:S2SPacket.PktRegisterServer)
  return target;
}

int PktRegisterServer::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:S2SPacket.PktRegisterServer)
  int total_size = 0;

  // optional int32 server_info = 1;
  if (this->server_info() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->server_info());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PktRegisterServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:S2SPacket.PktRegisterServer)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PktRegisterServer* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PktRegisterServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:S2SPacket.PktRegisterServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:S2SPacket.PktRegisterServer)
    MergeFrom(*source);
  }
}

void PktRegisterServer::MergeFrom(const PktRegisterServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:S2SPacket.PktRegisterServer)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.server_info() != 0) {
    set_server_info(from.server_info());
  }
}

void PktRegisterServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:S2SPacket.PktRegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PktRegisterServer::CopyFrom(const PktRegisterServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2SPacket.PktRegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PktRegisterServer::IsInitialized() const {

  return true;
}

void PktRegisterServer::Swap(PktRegisterServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PktRegisterServer::InternalSwap(PktRegisterServer* other) {
  std::swap(server_info_, other->server_info_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PktRegisterServer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PktRegisterServer_descriptor_;
  metadata.reflection = PktRegisterServer_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PktRegisterServer

// optional int32 server_info = 1;
void PktRegisterServer::clear_server_info() {
  server_info_ = 0;
}
 ::google::protobuf::int32 PktRegisterServer::server_info() const {
  // @@protoc_insertion_point(field_get:S2SPacket.PktRegisterServer.server_info)
  return server_info_;
}
 void PktRegisterServer::set_server_info(::google::protobuf::int32 value) {
  
  server_info_ = value;
  // @@protoc_insertion_point(field_set:S2SPacket.PktRegisterServer.server_info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace S2SPacket

// @@protoc_insertion_point(global_scope)
