// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_packet.proto

#ifndef PROTOBUF_server_5fpacket_2eproto__INCLUDED
#define PROTOBUF_server_5fpacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerPacket {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_server_5fpacket_2eproto();
void protobuf_AssignDesc_server_5fpacket_2eproto();
void protobuf_ShutdownFile_server_5fpacket_2eproto();

class PktRegisterServer;

// ===================================================================

class PktRegisterServer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerPacket.PktRegisterServer) */ {
 public:
  PktRegisterServer();
  virtual ~PktRegisterServer();

  PktRegisterServer(const PktRegisterServer& from);

  inline PktRegisterServer& operator=(const PktRegisterServer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PktRegisterServer& default_instance();

  void Swap(PktRegisterServer* other);

  // implements Message ----------------------------------------------

  inline PktRegisterServer* New() const { return New(NULL); }

  PktRegisterServer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PktRegisterServer& from);
  void MergeFrom(const PktRegisterServer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PktRegisterServer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 server_info = 1;
  void clear_server_info();
  static const int kServerInfoFieldNumber = 1;
  ::google::protobuf::int32 server_info() const;
  void set_server_info(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerPacket.PktRegisterServer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 server_info_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_server_5fpacket_2eproto();
  friend void protobuf_AssignDesc_server_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_server_5fpacket_2eproto();

  void InitAsDefaultInstance();
  static PktRegisterServer* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PktRegisterServer

// optional int32 server_info = 1;
inline void PktRegisterServer::clear_server_info() {
  server_info_ = 0;
}
inline ::google::protobuf::int32 PktRegisterServer::server_info() const {
  // @@protoc_insertion_point(field_get:ServerPacket.PktRegisterServer.server_info)
  return server_info_;
}
inline void PktRegisterServer::set_server_info(::google::protobuf::int32 value) {
  
  server_info_ = value;
  // @@protoc_insertion_point(field_set:ServerPacket.PktRegisterServer.server_info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerPacket

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_server_5fpacket_2eproto__INCLUDED
